name: CI

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Build and run tests

    steps:
      - uses: actions/checkout@v3

      - name: Start db
        run: docker-compose up -d db

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      # Run the npm ci command before building
      # the dotnet project, because the project
      # itself calls npm install if the node_modules
      # folder does not exist.
      - working-directory: ./src/ClientApp
        run: npm ci

      - run: dotnet build EWS.sln /warnaserror
      - run: dotnet test EWS.sln --no-build --verbosity normal
      - working-directory: ./src/ClientApp
        run: npm run build --if-present
      - working-directory: ./src/ClientApp
        run: npm run lint
      - working-directory: ./src/ClientApp
        run: npm test
